# Generated by Django 6.0.4 on 2026-05-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_alter_produto_preco_base'),
        ('usuarios', '0002_usuario_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente_nome', models.CharField(max_length=200)),
                ('cliente_cnpj', models.CharField(max_length=18)),
                ('status', models.CharField(choices=[('EM_DIGITACAO', 'Em Digitação'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EM_DIGITACAO', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='usuarios.perfilrepresentante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_vendas', to='catalogo.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
